apiVersion: batch/v1
kind: CronJob
metadata:
    name: bin
spec:
  schedule: "0 8 * * 0"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: bin
        spec:
          restartPolicy: OnFailure
          containers:
          - image: quay.io/kennedn/pebbletools
            name: bin
            workingDir: /usr/src/app
            command: ["python"]
            args: ["-u", "bin_collector.py"]
            volumeMounts:
            - name: bin-config-volume
              mountPath:  /usr/src/app/variables.py
              subPath: variables.py
          volumes:
          - name: bin-config-volume
            configMap:
              defaultMode: 420
              name: pebbletools-config

